// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoGl7Q96mmksnylNId24uHNhg7ztMNibA',
    appId: '1:171015317576:web:a734503034489ec796107d',
    messagingSenderId: '171015317576',
    projectId: 'pushnotif-3e5be',
    authDomain: 'pushnotif-3e5be.firebaseapp.com',
    storageBucket: 'pushnotif-3e5be.firebasestorage.app',
    measurementId: 'G-6LXZ6D7DVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR6uo2B4A5RJjt97z-cKGL-KJouq4OIZ0',
    appId: '1:171015317576:android:ed1eda0e010aceea96107d',
    messagingSenderId: '171015317576',
    projectId: 'pushnotif-3e5be',
    storageBucket: 'pushnotif-3e5be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARtbyHcTyO964DZ7fsy6s1oEAahCh6Ibk',
    appId: '1:171015317576:ios:6720788e0897f54096107d',
    messagingSenderId: '171015317576',
    projectId: 'pushnotif-3e5be',
    storageBucket: 'pushnotif-3e5be.firebasestorage.app',
    iosBundleId: 'com.example.ibpr',
  );
}
